### ISSUE TITLE
Dialogue Speed won't work in a song.

### ISSUE THREAD

**Issue by TheKamboy** [LeonGamerPS4/UnknownEngine#2]
### Describe your bug here.

When a song has dialogue, the speed won't be changed. It uses the default.
For some reason, the Dialogue Editor still will display the text at the speed chosen.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made BotPlay less laggy.

**Comment by LeonGamerPS4** [comment]
hm, it seems to work properly for me. can u show me a vid of it?

**Comment by LeonGamerPS4** [comment]
seems like it’s a psych issue. it’ll be fixed once psych 0.7 comes out
