### ISSUE TITLE
..score does nothing

### ISSUE THREAD

**Issue by Redefa** [LeonGamerPS4/UnknownEngine#21]
### Describe your problem here.

this is my first time using this engine
![image](https://user-images.githubusercontent.com/115251726/235625790-e3f8af12-4fca-4beb-b7ed-424dce98fbcd.png)
![image](https://user-images.githubusercontent.com/115251726/235625965-f50809a9-e2ce-4429-8c6b-dab00657bf50.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Redefa** [comment]
i don't think im doing wrong, it's perfectly work fine in psych engine

**Comment by LeonGamerPS4** [comment]
ah shit gotta fix that
