### ISSUE TITLE
wtf is this error, it wont compile

### ISSUE THREAD

**Issue by CJ77GT6R** [LeonGamerPS4/UnknownEngine#22]
### Describe your bug here.

when i put lime test windows it happends this error over here
source/ModifiersState.hx:34: characters 72-74 : Unknown identifier : XY
source/ModifiersState.hx:34: characters 72-74 : ... For optional function argument 'ScrollX'

### Command Prompt/Terminal logs (if existing)

```bash
source/ModifiersState.hx:34: characters 72-74 : Unknown identifier : XY
source/ModifiersState.hx:34: characters 72-74 : ... For optional function argument 'ScrollX'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by LeonGamerPS4** [comment]
shit it has to do with a pull request

**Comment by LeonGamerPS4** [comment]
i’ll fix it rn

**Comment by CJ77GT6R** [comment]
ok
