### ISSUE TITLE
Compil Error

### ISSUE THREAD

**Issue by SonicStyle2006** [LeonGamerPS4/UnknownEngine#25]
### Describe your bug here.

There's this one bug saying : 

source/ModifiersState.hx:34: characters 73-76 : Float should be flixel.util.FlxAxes
source/ModifiersState.hx:34: characters 73-76 : ... For optional function argument 'repeatAxes

Any solutions ?

### Command Prompt/Terminal logs (if existing)

```bash
source/ModifiersState.hx:34: characters 73-76 : Float should be flixel.util.FlxAxes
source/ModifiersState.hx:34: characters 73-76 : ... For optional function argument 'repeatAxes
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope lol

**Comment by Stefan2008Git** [comment]
I think you need to use ``XY`` on your checker background code for that
