### ISSUE TITLE
Can't compile game

### ISSUE THREAD

**Issue by Nightmare-boyfriend** [LeonGamerPS4/UnknownEngine#5]
### Describe your bug here.

Whenever I put 'lime test windows' it gives me this:  

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : For optional function argument 'updateFramerate'
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/options/BaseOptionsMenu.hx:34: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/BaseOptionsMenu.hx:34: characters 74-77 : For optional function argument 'repeatAxes'
source/OutdatedState.hx:21: characters 72-75 : Float should be flixel.util.FlxAxes
source/OutdatedState.hx:21: characters 72-75 : For optional function argument 'repeatAxes'
source/PlayState.hx:1695: characters 13-23 : Type not found : MP4Handler
source/options/OptionsState.hx:40: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/OptionsState.hx:40: characters 74-77 : For optional function argument 'repeatAxes'
source/options/NotesSubState.hx:34: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/NotesSubState.hx:34: characters 74-77 : For optional function argument 'repeatAxes'
source/options/ControlsSubState.hx:36: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/ControlsSubState.hx:36: characters 74-77 : For optional function argument 'repeatAxes'
source/MainMenuState.hx:52: characters 72-75 : Float should be flixel.util.FlxAxes
source/MainMenuState.hx:52: characters 72-75 : For optional function argument 'repeatAxes'
source/AchievementsMenuState.hx:32: characters 71-74 : Float should be flixel.util.FlxAxes
source/AchievementsMenuState.hx:32: characters 71-74 : For optional function argument 'repeatAxes'
Is there a wy to fix this please let me know.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by LeonGamerPS4** [comment]
hmm

**Comment by LeonGamerPS4** [comment]
did you install all required programs properly?

**Comment by MemeHoovy** [comment]
first, don't use flixel 5.0.0, and use the haxelib version of hxCodec

**Comment by Nightmare-boyfriend** [comment]
when i install flixel its version is 9.2.0 and i install hxCodec from the psych engine source code

**Comment by MemeHoovy** [comment]
that's OpenFL, not flixel

**Comment by Nightmare-boyfriend** [comment]
i tired it again and make sure i install all the commands

**Comment by Nightmare-boyfriend** [comment]
oh my mistake its version is 5.0.1

**Comment by Nightmare-boyfriend** [comment]
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/options/BaseOptionsMenu.hx:34: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/BaseOptionsMenu.hx:34: characters 74-77 : ... For optional function argument 'repeatAxes'
this what i get when I do "lime test windows"

**Comment by MemeHoovy** [comment]
haxelib install flixel 4.11.0

**Comment by Nightmare-boyfriend** [comment]
ill try it

**Comment by Nightmare-boyfriend** [comment]
Same thing I also try with psych engine and it tells me the same thing

**Comment by Nightmare-boyfriend** [comment]
at first this is the only come up: 
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'

**Comment by Nightmare-boyfriend** [comment]
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
source/options/BaseOptionsMenu.hx:34: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/BaseOptionsMenu.hx:34: characters 74-77 : ... For optional function argument 'repeatAxes'

**Comment by Nightmare-boyfriend** [comment]
it shows me errors about flixel-addons and source/options/BaseOptionsMenu.hx:34: characters 74-77 : Float should be flixel.util.FlxAxes
source/options/BaseOptionsMenu.hx:34: characters 74-77 : ... For optional function argument 'repeatAxes'

**Comment by Nightmare-boyfriend** [comment]
Nevermind I got it to compile!

**Comment by Nightmare-boyfriend** [comment]
i install flixel-addons 2.11.0 and it compiled
